# this is a comment

name: first github action

on: 
    push:
        branches: 
        - main
    
jobs:
    my-first-job:
        runs-on: ubuntu-18.04
        steps:
           - run: echo "this is the start"
    my-second-job:
        runs-on: ubuntu-18.04
        steps:
            - run: echo this is second & last job
